# Generated by Django 3.2.5 on 2021-09-11 22:25

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_grupal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
                ('members', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=255)),
                ('score', models.FloatField()),
                ('groupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_grupal.group')),
            ],
        ),
        migrations.RemoveField(
            model_name='academicgroup',
            name='info_acad',
        ),
        migrations.DeleteModel(
            name='InfoAcademica',
        ),
        migrations.RemoveField(
            model_name='recreativeactivity',
            name='info_acad',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='info_acad',
        ),
        migrations.DeleteModel(
            name='AcademicGroup',
        ),
        migrations.DeleteModel(
            name='RecreativeActivity',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
