# Generated by Django 3.2.6 on 2021-09-02 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=255)),
                ('faculty', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('academicLevel', models.CharField(max_length=255)),
                ('idProfessor', models.CharField(max_length=255)),
                ('info_acad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_academica.infoacademica')),
            ],
        ),
        migrations.CreateModel(
            name='RecreativeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('info_acad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_academica.infoacademica')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDirector', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('info_acad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_academica.infoacademica')),
            ],
        ),
    ]
