# Generated by Django 3.2.5 on 2021-09-11 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil_usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=255)),
                ('countryOfBirth', models.CharField(max_length=255)),
                ('stateOfBirth', models.CharField(max_length=255)),
                ('birthDate', models.CharField(max_length=255)),
                ('maritalStatus', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('livesWith', models.CharField(max_length=255)),
                ('works', models.BooleanField()),
                ('schoolCity', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('classId', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('grade', models.FloatField()),
                ('academic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_usuario.academicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TermSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicDegree', models.CharField(max_length=255)),
                ('program', models.CharField(max_length=255)),
                ('term', models.CharField(max_length=255)),
                ('termAverage', models.FloatField()),
                ('average', models.FloatField()),
                ('approvedCredits', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('academicSituation', models.CharField(max_length=255)),
                ('academic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_usuario.academicinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idResource', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('library_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil_usuario.libraryhistory')),
            ],
        ),
        migrations.RemoveField(
            model_name='academicgroup',
            name='info_acad',
        ),
        migrations.DeleteModel(
            name='InfoAcademica',
        ),
        migrations.RemoveField(
            model_name='recreativeactivity',
            name='info_acad',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='info_acad',
        ),
        migrations.DeleteModel(
            name='AcademicGroup',
        ),
        migrations.DeleteModel(
            name='RecreativeActivity',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
