# Generated by Django 2.2.14 on 2021-11-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomemendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('userId', models.CharField(max_length=255)),
                ('dewey', models.CharField(max_length=255)),
                ('themes', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='academicgroup',
            name='info_acad',
        ),
        migrations.DeleteModel(
            name='InfoAcademica',
        ),
        migrations.RemoveField(
            model_name='recreativeactivity',
            name='info_acad',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='info_acad',
        ),
        migrations.DeleteModel(
            name='AcademicGroup',
        ),
        migrations.DeleteModel(
            name='RecreativeActivity',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
