# Generated by Django 3.2.6 on 2021-09-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBasica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.CharField(max_length=255)),
                ('countryOfBirth', models.CharField(max_length=255)),
                ('stateOfBirth', models.CharField(max_length=255)),
                ('birthDate', models.CharField(max_length=255)),
                ('maritalStatus', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('livesWith', models.CharField(max_length=255)),
                ('works', models.BooleanField()),
                ('schoolCity', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=2)),
                ('gender', models.CharField(max_length=255)),
            ],
        ),
    ]
